### ISSUE TITLE
some false-true

### ISSUE THREAD

**Issue by koliwbr** [p1ngul1n0/blackbird#34]
![image](https://user-images.githubusercontent.com/61465776/184189524-b234412e-de77-4696-bea3-fb021d17baad.png)
YouTube, TikTok, Pinterest and sometimes other sites return True 
('14c7880a71ed2bdae6741b3976907770c7c013af8cefd0e8' is random hexadecimal)

**Comment by p1ngul1n0** [comment]
Hi Koliwbr, i aware of false positives, sometimes they may happen because of network behavior, others by the test itself.

It's very hard to create a test that will always give real results, this is because the response of the server may behave differently based on the region you are in some cases. This is one of the main reasons I need collaboration, I can't predict all the behaviors.

I will look into it, but in the meantime you can help me verify why this is happening, just check the [data.json](https://github.com/p1ngul1n0/blackbird/blob/main/data.json) file to see the tests and try to improve them.

Thanks in advance!

**Comment by wymiotkloaki** [comment]
currently the 4 sites giving false positives are: tiktok, pinterest. protonmail and youtube - they are on my todo list, but feel free to jump in.
@p1ngul1n0 i have an idea how to unit test it, but it will require some changes to the data.json file, might open PR about this at some point.
