### ISSUE TITLE
NameError; name 'arguments' is not defined; arguments.csv

### ISSUE THREAD

**Issue by Tobi0878** [p1ngul1n0/blackbird#51]
Hi,
Installation with git clone: an error occurs after the usernames have been checked, see screenshot
The installation with docker works without error

![blackbird_issue1](https://user-images.githubusercontent.com/132354641/235660687-e0a62f52-4977-47da-a3dc-552a0558a52a.png)

**Comment by Pitastic** [comment]
Same here (fresh install in my own Docker today).

The error means, that the commandline arguments object from `argparse` is unknown at this point of execution. Since it is async I woul recommend to pass that (or better just the CSV flag) in at this function call [here](https://github.com/p1ngul1n0/blackbird/blob/main/blackbird.py#L203) like so:

```
# In the definition
async def findUsername(username, interfaceType, flag_csv=False)

# and the call (in blackbird.py - webserver.py need not to be changed)
asyncio.run(findUsername(arguments.username, interfaceType, arguments.csv))
```

Works well for me after these changes !

**Comment by Pitastic** [comment]
Here you are :)
